# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: db-credentials
#   namespace: backend
# spec:
#   refreshInterval: 1h0m0s
#   secretStoreRef:
#     name: aws-secrets
#     kind: SecretStore
#   target:
#     name: db-credentials     # Kubernetes Secret name created
#     creationPolicy: Owner
#   data:
#     - secretKey: DB_USERNAME
#       remoteRef:
#         key: eks-benchmark-baseline-db-credentials
#         property: username
#     - secretKey: DB_PASSWORD
#       remoteRef:
#         key: eks-benchmark-baseline-db-credentials
#         property: password
#     - secretKey: DB_HOST
#       remoteRef:
#         key: eks-benchmark-baseline-db-credentials
#         property: host
#     - secretKey: DB_PORT
#       remoteRef:
#         key: eks-benchmark-baseline-db-credentials
#         property: port
#     - secretKey: DB_NAME
#       remoteRef:
#         key: eks-benchmark-baseline-db-credentials
#         property: dbname