
# configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: backend
data:
  APP_NAME: "eks-benchmark"
  ENV: "dev"
  DEBUG: "true"
  LOG_LEVEL: "info"

  POSTGRES__HOST: "pgdb_host"
  POSTGRES__PORT: "5432"
  POSTGRES__DB: "pgdb_db"
  POSTGRES__USER: "pgdb_user"

  POOL_SIZE: "5"
  MAX_OVERFLOW: "0"
  WORKER: "1"
---
# secrets
apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  namespace: backend
type: Opaque
stringData:
  POSTGRES__PASSWORD: "pgdb_pwd"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: backend
  labels:
    app: fastapi
spec:
  replicas: 1  # dev default
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: 099139718958.dkr.ecr.ca-central-1.amazonaws.com/auto-benchmark:fastapi-baseline
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          # env from configmap + secret
          envFrom:
            - configMapRef:
                name: fastapi-config
            - secretRef:
                name: fastapi-secret

          # env:
          #   - name: DB_HOST
          #     valueFrom:
          #       secretKeyRef:
          #         name: db-credentials
          #         key: DB_HOST
          #   - name: DB_PORT
          #     valueFrom:
          #       secretKeyRef:
          #         name: db-credentials
          #         key: DB_PORT
          #   - name: DB_NAME
          #     valueFrom:
          #       secretKeyRef:
          #         name: db-credentials
          #         key: DB_NAME
          #   - name: DB_USERNAME
          #     valueFrom:
          #       secretKeyRef:
          #         name: db-credentials
          #         key: DB_USERNAME
          #   - name: DB_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: db-credentials
          #         key: DB_PASSWORD


          # health check: ECS used curl; in k8s we can do HTTP probes directly
          readinessProbe:
            httpGet:
              path: /api/health/
              port: 8000
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
            initialDelaySeconds: 10

          livenessProbe:
            httpGet:
              path: /api/health/
              port: 8000
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
            initialDelaySeconds: 30

          # ECS startPeriod=90 -> approximate in k8s with startupProbe
          startupProbe:
            httpGet:
              path: /api/health/
              port: 8000
            periodSeconds: 10
            failureThreshold: 9  # ~90s total (9 * 10s)

          # stopTimeout: 30 -> terminationGracePeriodSeconds
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]

          # resources: map ECS cpu/mem to k8s requests/limits (placeholders)
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: backend
  labels:
    app: fastapi
spec:
  selector:
    app: fastapi
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP