# .github/workflows/job_destroy.yaml
name: Job-Destroy Resources

on:
    workflow_call:
        inputs:
            project:
                description: "Project name"
                required: true
                type: string
            arch:
                description: "Architecture"
                required: true
                type: string
            aws_region:
                description: "AWS region"
                type: string
                default: "ca-central-1"
        secrets:
            db_name:
                description: "Database name"
            db_username:
                description: "Database username"
            db_password:
                description: "Database password"
            db_app_pwd:
                description: "App user password"
            db_readonly_pwd:
                description: "Readonly user password"
            cf_api_token:
                description: "Cloudflare API token"
            cf_zone_id:
                description: "Cloudflare zone id"
            aws_tf_role_arn:
                description: "AWS role for tf"
            aws_backend_bucket:
                description: "AWS bucket for tf remote backend"
jobs:
    destroy_k8s:
        name: Destroy K8s ${{ inputs.arch }}
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.aws_tf_role_arn}}
                  aws-region: ${{ inputs.aws_region }}

            - name: Set up kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: "v1.34.0"

            - name: Update kubeconfig
              run: |
                  echo "${{ inputs.project }}-${{ inputs.arch }}"
                  aws eks update-kubeconfig --name "${{ inputs.project }}-${{ inputs.arch }}" --region ${{ inputs.aws_region }}

            # - name: Install Helm
            #   uses: azure/setup-helm@v1
            #   with:
            #       version: v3.20.0

            - name: Deploy with script
              env:
                  REGION: ${{ inputs.aws_region }}
                  CLUSTER_NAME: ${{ inputs.project }}-${{ inputs.arch }}
                  ARCH: ${{ inputs.arch }}
              run: |
                  bash manifest/destroy.sh

    destroy_infra:
        name: Destroy Infra ${{ inputs.arch }}
        needs:
            - destroy_k8s
        runs-on: ubuntu-latest
        timeout-minutes: 60
        env:
            TF_VERSION: 1.14.0
            TF_DIR: baseline/${{ inputs.arch }}
            TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache
            TF_VAR_aws_region: ${{ inputs.AWS_REGION }}
            TF_VAR_env: ${{ inputs.arch }}
            TF_VAR_db_name: ${{ secrets.db_name }}
            TF_VAR_db_username: ${{ secrets.db_username }}
            TF_VAR_db_password: ${{ secrets.db_password }}
            TF_VAR_db_app_pwd: ${{ secrets.db_app_pwd }}
            TF_VAR_db_readonly_pwd: ${{ secrets.db_readonly_pwd }}
            TF_VAR_cloudflare_api_token: ${{ secrets.cf_api_token }}
            TF_VAR_cloudflare_zone_id: ${{ secrets.cf_zone_id }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ${{ env.TF_VERSION }}

            - name: Configure AWS credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.aws_tf_role_arn}}
                  aws-region: ${{ inputs.aws_region }}

            - name: Configure Terraform plugin cache
              run: |
                  mkdir -pv ${{ env.TF_PLUGIN_CACHE_DIR }}
                  echo 'plugin_cache_dir = "${{ env.TF_PLUGIN_CACHE_DIR }}"' > ~/.terraformrc

            - name: Cache Terraform plugins
              uses: actions/cache@v4
              with:
                  path: ${{ env.TF_PLUGIN_CACHE_DIR }}
                  key: ${{ runner.os }}-terraform-${{ env.TF_VERSION }}-${{ inputs.arch }}-${{ hashFiles('aws/.terraform.lock.hcl') }}

            - name: Terraform init - S3 backend
              working-directory: ${{ env.TF_DIR }}
              run: |
                  terraform init -reconfigure -input=false \
                  -backend-config="bucket=${{ secrets.AWS_BACKEND_BUCKET }}" \
                  -backend-config="region=${{ inputs.AWS_REGION }}" \
                  -backend-config="key=${{ inputs.project }}/${{ inputs.arch }}/terraform.tfstate" \
                  -backend-config="encrypt=true"

            - name: Terraform Validate
              working-directory: ${{ env.TF_DIR }}
              run: |
                  terraform fmt -check -recursive -no-color
                  terraform validate -no-color

            - name: Destroy - Terraform Plan
              working-directory: ${{ env.TF_DIR }}
              id: destroy-plan
              run: terraform plan -out=tfplan-destroy -input=false -no-color -destroy

            - name: Destroy - Show plan (JSON)
              working-directory: ${{ env.TF_DIR }}
              run: terraform show -json tfplan-destroy > tfplan-destroy.json

            - name: Destroy - Save plan artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: tfplan-destroy-${{ env.TF_VAR_env }}
                  path: |
                      ${{ env.TF_DIR }}/tfplan-destroy
                      ${{ env.TF_DIR }}/tfplan-destroy.json
                  retention-days: 3

            - name: Destroy - Terraform Apply
              working-directory: ${{ env.TF_DIR }}
              run: terraform apply -auto-approve -no-color tfplan-destroy
