# .github/workflows/job_deploy.yaml
name: Job-Deploy Resources

on:
    workflow_call:
        inputs:
            project:
                description: "Project name"
                required: true
                type: string
            arch:
                description: "Architecture"
                required: true
                type: string
            aws_region:
                description: "AWS region"
                type: string
                default: "ca-central-1"
        secrets:
            db_name:
                description: "Database name"
            db_username:
                description: "Database username"
            db_password:
                description: "Database password"
            db_app_pwd:
                description: "App user password"
            db_readonly_pwd:
                description: "Readonly user password"
            cf_api_token:
                description: "Cloudflare API token"
            cf_zone_id:
                description: "Cloudflare zone id"
            aws_tf_role_arn:
                description: "AWS role for tf"
            aws_backend_bucket:
                description: "AWS bucket for tf remote backend"
        # outputs:
        #     base_url:
        #         description: "A description of the output"
        #         value: ${{ jobs.deploy.outputs.base_url }}
jobs:
    deploy_infra:
        name: Deploy ${{ inputs.arch }}
        runs-on: ubuntu-latest
        timeout-minutes: 60
        env:
            TF_VERSION: 1.14.0
            TF_DIR: infra/${{ inputs.arch }}
            TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache
            TF_VAR_aws_region: ${{ inputs.AWS_REGION }}
            TF_VAR_env: ${{ inputs.arch }}
            TF_VAR_db_name: ${{ secrets.db_name }}
            TF_VAR_db_username: ${{ secrets.db_username }}
            TF_VAR_db_password: ${{ secrets.db_password }}
            TF_VAR_db_app_pwd: ${{ secrets.db_app_pwd }}
            TF_VAR_db_readonly_pwd: ${{ secrets.db_readonly_pwd }}
            TF_VAR_cloudflare_api_token: ${{ secrets.cf_api_token }}
            TF_VAR_cloudflare_zone_id: ${{ secrets.cf_zone_id }}
        outputs:
            vpc_id: ${{ steps.tf-outputs.outputs.vpc_id }}
            iam_role_lbc: ${{ steps.tf-outputs.outputs.lbc_arn }}
            iam_role_eso: ${{ steps.tf-outputs.outputs.eso_arn }}
            cluster_name: ${{ steps.tf-outputs.outputs.cluster_name }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ${{ env.TF_VERSION }}

            - name: Configure AWS credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.aws_tf_role_arn}}
                  aws-region: ${{ inputs.aws_region }}

            - name: Configure Terraform plugin cache
              run: |
                  mkdir -pv ${{ env.TF_PLUGIN_CACHE_DIR }}
                  echo 'plugin_cache_dir = "${{ env.TF_PLUGIN_CACHE_DIR }}"' > ~/.terraformrc

            - name: Cache Terraform plugins
              uses: actions/cache@v4
              with:
                  path: ${{ env.TF_PLUGIN_CACHE_DIR }}
                  key: ${{ runner.os }}-terraform-${{ env.TF_VERSION }}-${{ inputs.arch }}-${{ hashFiles('aws/.terraform.lock.hcl') }}

            - name: Terraform init - S3 backend
              working-directory: ${{ env.TF_DIR }}
              run: |
                  terraform init -reconfigure -input=false \
                    -backend-config="bucket=${{ secrets.AWS_BACKEND_BUCKET }}" \
                    -backend-config="region=${{ inputs.AWS_REGION }}" \
                    -backend-config="key=${{ inputs.project }}/${{ inputs.arch }}/terraform.tfstate" \
                    -backend-config="encrypt=true"

            - name: Terraform Validate
              working-directory: ${{ env.TF_DIR }}
              run: |
                  terraform fmt -check -recursive -no-color
                  terraform validate -no-color

            - name: Deploy - Terraform Plan
              working-directory: ${{ env.TF_DIR }}
              id: deploy-plan
              run: terraform plan -out=tfplan -input=false -no-color

            - name: Deploy - Show plan (JSON)
              working-directory: ${{ env.TF_DIR }}
              run: terraform show -json tfplan > tfplan.json

            - name: Deploy - Save plan artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: "tfplan-deploy-${{ env.TF_VAR_env }}"
                  path: |
                      ${{ env.TF_DIR }}/tfplan
                      ${{ env.TF_DIR }}/tfplan.json
                  overwrite: true
                  retention-days: 3

            - name: Deploy - Terraform Apply
              working-directory: ${{ env.TF_DIR }}
              run: terraform apply -auto-approve -no-color tfplan

            - name: Export Terraform Outputs
              id: tf-outputs
              working-directory: ${{ env.TF_DIR }}
              run: |
                  echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT
                  echo "VPC_ID=$(terraform output -raw vpc_id)" >> $GITHUB_OUTPUT
                  echo "LBC_ARN=$(terraform output -raw iam_role_lbc)" >> $GITHUB_OUTPUT
                  echo "ESO_ARN=$(terraform output -raw iam_role_eso)" >> $GITHUB_OUTPUT

    deploy_k8s:
        name: Deploy K8s ${{ inputs.arch }}
        needs:
            - deploy_infra
        runs-on: ubuntu-latest
        timeout-minutes: 60
        permissions:
            contents: read
            id-token: write # Required for OIDC authentication
        env:
            REGION: ${{ inputs.aws_region }}
            CLUSTER_NAME: ${{ needs.deploy_infra.outputs.cluster_name }}
            IAM_LBC_ROLE_ARN: ${{ needs.deploy_infra.outputs.iam_role_lbc }}
            IAM_ESO_ROLE_ARN: ${{ needs.deploy_infra.outputs.iam_role_eso }}
            VPC_ID: ${{ needs.deploy_infra.outputs.vpc_id }}
            CF_TOKEN: ${{ secrets.cf_api_token }}
            ARCH: ${{ inputs.arch }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.aws_tf_role_arn}}
                  aws-region: ${{ inputs.aws_region }}

            - name: Set up kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: "v1.34.0"

            - name: Update kubeconfig
              run: |
                  echo "${{ inputs.project }}-${{ inputs.arch }}"
                  aws eks update-kubeconfig --name "${{ inputs.project }}-${{ inputs.arch }}" --region ${{ inputs.aws_region }}

            - name: Install Helm
              uses: azure/setup-helm@v1
              with:
                  version: v3.20.0

            - name: Deploy with scritp
              run: |
                  bash manifest/init.sh
            
            - name: Initial RDS
              run: |
                kubectl apply -f manifest/job/flyway.yaml