# .github/workflow/wf-testing.yaml
name: Workflow-Auto Testing

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     # - "main"
  #     - "testing"

# multiple trigger
concurrency:
  group: wf-testing-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true # Cancel older runs

jobs:
  deploy_infra:
    name: Deploy Resources
    uses: ./.github/workflows/job_deploy.yaml
    permissions:
      contents: read
      id-token: write # OIDC
    strategy:
      fail-fast: false
      matrix:
        solution:
          - arch: baseline
          # - arch: scale
          # - arch: redis
          # - arch: kafka
    with:
      project: ${{ vars.PROJECT}}
      arch: ${{ matrix.solution.arch }}
      aws_region: ${{ vars.AWS_REGION }}
    secrets:
      db_name: ${{ secrets.DB_NAME }}
      db_username: ${{ secrets.DB_USERNAME }}
      db_password: ${{ secrets.DB_PASSWORD }}
      db_app_pwd: ${{ secrets.DB_APP_PWD }}
      db_readonly_pwd: ${{ secrets.DB_READONLY_PWD }}
      cf_api_token: ${{ secrets.CF_API_TOKEN }}
      cf_zone_id: ${{ secrets.CF_ZONE_ID }}
      aws_tf_role_arn: ${{ secrets.AWS_TF_ROLE_ARN }}
      aws_backend_bucket: ${{ vars.AWS_BACKEND_BUCKET }}

  # smoke_testing:
  #   name: Smoke Testing
  #   needs: deploy
  #   uses: ./.github/workflows/job_test_smoke.yaml
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       solution:
  #         - env: baseline
  #           base_url: "https://eks-benchmark-baseline.arguswatcher.net"
  #         # - env: scale
  #         #   base_url: "https://eks-benchmark-scale.arguswatcher.net"
  #         # - env: redis
  #         #   base_url: "https://eks-benchmark-redis.arguswatcher.net"
  #         # - env: kafka
  #         #   base_url: "https://eks-benchmark-kafka.arguswatcher.net"
  #   with:
  #     env: ${{ matrix.solution.env }}
  #     base_url: ${{ matrix.solution.base_url }}

  # reset_for_read:
  #   name: Reset Resources for the Writing Testing
  #   needs:
  #     - smoke_testing
  #   # only when smoke testing success
  #   if: ${{ always() && needs.smoke_testing.result == 'success' }}
  #   uses: ./.github/workflows/job_reset.yaml
  #   permissions:
  #     contents: read
  #     id-token: write # OIDC
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       solution:
  #         - env: baseline
  #         # - env: tune
  #         - env: scale
  #         - env: redis
  #         - env: kafka
  #   with:
  #     project: ${{ vars.PROJECT}}
  #     env: ${{ matrix.solution.env }}
  #     aws_region: ${{ vars.AWS_REGION }}
  #   secrets:
  #     db_name: ${{ secrets.DB_NAME }}
  #     db_username: ${{ secrets.DB_USERNAME }}
  #     db_password: ${{ secrets.DB_PASSWORD }}
  #     db_app_pwd: ${{ secrets.DB_APP_PWD }}
  #     db_readonly_pwd: ${{ secrets.DB_READONLY_PWD }}
  #     cf_api_token: ${{ secrets.CF_API_TOKEN }}
  #     cf_zone_id: ${{ secrets.CF_ZONE_ID }}
  #     aws_tf_role_arn: ${{ secrets.AWS_TF_ROLE_ARN }}
  #     aws_backend_bucket: ${{ vars.AWS_BACKEND_BUCKET }}

  # performance_testing_read:
  #   name: Performance Testing-Read
  #   needs:
  #     - smoke_testing
  #     - reset_for_read
  #   #   only when smoke success
  #   if: ${{ needs.smoke_testing.result == 'success' }}
  #   uses: ./.github/workflows/job_test_performance.yaml
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       solution:
  #         - env: baseline
  #           base_url: "https://benchmark-baseline.arguswatcher.net"
  #           test_report: baseline_cicd_read.html
  #         - env: scale
  #           base_url: "https://benchmark-scale.arguswatcher.net"
  #           test_report: scale_cicd_read.html
  #         # - env: tune
  #         #   base_url: "https://benchmark-tune.arguswatcher.net"
  #         #   test_report: tune_cicd_read.html
  #         - env: redis
  #           base_url: "https://benchmark-redis.arguswatcher.net"
  #           test_report: redis_cicd_read.html
  #         - env: kafka
  #           base_url: "https://benchmark-kafka.arguswatcher.net"
  #           test_report: kafka_cicd_read.html
  #   with:
  #     base_url: ${{ matrix.solution.base_url }}
  #     env: ${{ matrix.solution.env }}
  #     test_report: ${{ matrix.solution.test_report }}
  #     test_script: test_hp_read.js

  # reset_for_write:
  #   name: Reset Resources for the Writing Testing
  #   needs:
  #     - smoke_testing
  #     # - performance_testing_read
  #   # only when smoke testing success
  #   if: ${{ always() && needs.smoke_testing.result == 'success' }}
  #   uses: ./.github/workflows/job_reset.yaml
  #   permissions:
  #     contents: read
  #     id-token: write # OIDC
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       solution:
  #         - env: baseline
  #         # - env: tune
  #         - env: scale
  #         - env: redis
  #         - env: kafka
  #   with:
  #     project: ${{ vars.PROJECT}}
  #     env: ${{ matrix.solution.env }}
  #     aws_region: ${{ vars.AWS_REGION }}
  #   secrets:
  #     db_name: ${{ secrets.DB_NAME }}
  #     db_username: ${{ secrets.DB_USERNAME }}
  #     db_password: ${{ secrets.DB_PASSWORD }}
  #     db_app_pwd: ${{ secrets.DB_APP_PWD }}
  #     db_readonly_pwd: ${{ secrets.DB_READONLY_PWD }}
  #     cf_api_token: ${{ secrets.CF_API_TOKEN }}
  #     cf_zone_id: ${{ secrets.CF_ZONE_ID }}
  #     aws_tf_role_arn: ${{ secrets.AWS_TF_ROLE_ARN }}
  #     aws_backend_bucket: ${{ vars.AWS_BACKEND_BUCKET }}

  # performance_testing_write:
  #   name: Performance Testing-Write
  #   needs:
  #     - smoke_testing
  #     - reset_for_write
  #   # only when smoke testing success
  #   if: ${{ always() && needs.smoke_testing.result == 'success' }}
  #   uses: ./.github/workflows/job_test_performance.yaml
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       solution:
  #         - env: baseline
  #           base_url: "https://benchmark-baseline.arguswatcher.net"
  #           test_report: baseline_cicd_write.html
  #         - env: scale
  #           base_url: "https://benchmark-scale.arguswatcher.net"
  #           test_report: scale_cicd_write.html
  #         # - env: tune
  #         #   base_url: "https://benchmark-tune.arguswatcher.net"
  #         #   test_report: tune_cicd_write.html
  #         - env: redis
  #           base_url: "https://benchmark-redis.arguswatcher.net"
  #           test_report: redis_cicd_write.html
  #         - env: kafka
  #           base_url: "https://benchmark-kafka.arguswatcher.net"
  #           test_report: kafka_cicd_write.html
  #   with:
  #     base_url: ${{ matrix.solution.base_url }}
  #     env: ${{ matrix.solution.env }}
  #     test_report: ${{ matrix.solution.test_report }}
  #     test_script: test_hp_write.js

  # reset_for_mixed:
  #   name: Reset Resources for the Mixed Testing
  #   needs:
  #     - smoke_testing
  #     - performance_testing_write
  #   # only when smoke testing success
  #   if: ${{ always() && needs.smoke_testing.result == 'success' }}
  #   uses: ./.github/workflows/job_reset.yaml
  #   permissions:
  #     contents: read
  #     id-token: write # OIDC
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       solution:
  #         - env: baseline
  #         # - env: tune
  #         - env: scale
  #         - env: redis
  #         - env: kafka
  #   with:
  #     project: ${{ vars.PROJECT}}
  #     env: ${{ matrix.solution.env }}
  #     aws_region: ${{ vars.AWS_REGION }}
  #   secrets:
  #     db_name: ${{ secrets.DB_NAME }}
  #     db_username: ${{ secrets.DB_USERNAME }}
  #     db_password: ${{ secrets.DB_PASSWORD }}
  #     db_app_pwd: ${{ secrets.DB_APP_PWD }}
  #     db_readonly_pwd: ${{ secrets.DB_READONLY_PWD }}
  #     cf_api_token: ${{ secrets.CF_API_TOKEN }}
  #     cf_zone_id: ${{ secrets.CF_ZONE_ID }}
  #     aws_tf_role_arn: ${{ secrets.AWS_TF_ROLE_ARN }}
  #     aws_backend_bucket: ${{ vars.AWS_BACKEND_BUCKET }}

  # performance_testing_mixed:
  #   name: Performance Testing-Mixed
  #   needs:
  #     - smoke_testing
  #     # - reset_for_mixed
  #   if: ${{ always() && needs.smoke_testing.result == 'success' }}
  #   uses: ./.github/workflows/job_test_performance.yaml
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       solution:
  #         - env: baseline
  #           base_url: "https://benchmark-baseline.arguswatcher.net"
  #           test_report: baseline_cicd_mixed.html
  #         - env: scale
  #           base_url: "https://benchmark-scale.arguswatcher.net"
  #           test_report: scale_cicd_mixed.html
  #         # - env: tune
  #         #   base_url: "https://benchmark-tune.arguswatcher.net"
  #         #   test_report: tune_cicd_mixed.html
  #         - env: redis
  #           base_url: "https://benchmark-redis.arguswatcher.net"
  #           test_report: redis_cicd_mixed.html
  #         - env: kafka
  #           base_url: "https://benchmark-kafka.arguswatcher.net"
  #           test_report: kafka_cicd_mixed.html
  #   with:
  #     base_url: ${{ matrix.solution.base_url }}
  #     env: ${{ matrix.solution.env }}
  #     test_report: ${{ matrix.solution.test_report }}
  #     test_script: test_hp_mixed.js

# debug: remove upload s3

  # destroy:
  #   name: Destroy Resources
  #   needs:
  #     - smoke_testing
  #     - performance_testing_mixed
  #   if: >-
  #     ${{
  #       always() &&
  #       (
  #         needs.smoke_testing.result != 'success' ||
  #         needs.performance_testing_mixed.result != 'skipped'
  #       )
  #     }}
  #   uses: ./.github/workflows/job_destroy.yaml
  #   permissions:
  #     contents: read
  #     id-token: write # OIDC
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       solution:
  #         - env: baseline
  #         # - env: tune
  #         - env: scale
  #         - env: redis
  #         - env: kafka
  #   with:
  #     project: ${{ vars.PROJECT}}
  #     env: ${{ matrix.solution.env }}
  #     aws_region: ${{ vars.AWS_REGION }}
  #   secrets:
  #     db_name: ${{ secrets.DB_NAME }}
  #     db_username: ${{ secrets.DB_USERNAME }}
  #     db_password: ${{ secrets.DB_PASSWORD }}
  #     db_app_pwd: ${{ secrets.DB_APP_PWD }}
  #     db_readonly_pwd: ${{ secrets.DB_READONLY_PWD }}
  #     cf_api_token: ${{ secrets.CF_API_TOKEN }}
  #     cf_zone_id: ${{ secrets.CF_ZONE_ID }}
  #     aws_tf_role_arn: ${{ secrets.AWS_TF_ROLE_ARN }}
  #     aws_backend_bucket: ${{ vars.AWS_BACKEND_BUCKET }}
